### ISSUE TITLE
How to read json payload from gitlab webhook in Jenkins

### ISSUE THREAD

**Issue by AIKiller** [jenkinsci/gitlab-hook-plugin#52]
I have a job using jenkins pipeline to deploy my project. now, I plan to use gitlab-hook-plugin to monitor the submission of projects on gitlab service.
Once a user submits a project change, Jenkins reads the submit parameters and performs other operations according to the type of submission, for example: build and test.
But then there is a problem, how do I read the parameters of the project change , such as submit log, branch, user name and other information.

**Comment by javiplx** [comment]
Actually, that is what the plugin makes: read the payload and take some actions. So, it is not posible to access payload details because they are actually used to trigger the Jenkins job. Seems that what you actually want is to write your own version of the plugin to take the actions you are interested on.
In particular, this plugin is a Jenkins 1.x one and is not integrated with current pipelines. It just executes all jobs that match the incoming payload (url & branch in the simplest case).
